/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package de.btu.swt.graph.ui;

import de.btu.swt.graph.api.GraphModel;
import de.btu.swt.graph.api.GraphNode;
import de.btu.swt.graph.api.GraphService;
import java.awt.BorderLayout;
import org.netbeans.api.settings.ConvertAsProperties;
import org.openide.awt.ActionID;
import org.openide.awt.ActionReference;
import org.openide.explorer.ExplorerManager;
import org.openide.explorer.view.BeanTreeView;
import org.openide.nodes.AbstractNode;
import org.openide.nodes.Children;
import org.openide.util.Lookup;
import org.openide.util.NbBundle.Messages;
import org.openide.windows.TopComponent;

/**
 * Top component which displays something.
 */
@ConvertAsProperties(
        dtd = "-//de.btu.swt.graph.ui//TreeView//EN",
        autostore = false
)
@TopComponent.Description(
        preferredID = "TreeViewTopComponent",
        //iconBase="SET/PATH/TO/ICON/HERE",
        persistenceType = TopComponent.PERSISTENCE_ALWAYS
)
@TopComponent.Registration(mode = "explorer", openAtStartup = true)
@ActionID(category = "Window", id = "de.btu.swt.graph.ui.TreeViewTopComponent")
@ActionReference(path = "Menu/Window" /*, position = 333 */)
@TopComponent.OpenActionRegistration(
        displayName = "#CTL_TreeViewAction",
        preferredID = "TreeViewTopComponent"
)
@Messages({
    "CTL_TreeViewAction=TreeView",
    "CTL_TreeViewTopComponent=TreeView Window",
    "HINT_TreeViewTopComponent=This is a TreeView window"
})
public final class TreeViewTopComponent extends TopComponent implements ExplorerManager.Provider {

    private final BeanTreeView treeView;
    private final ExplorerManager explorer;
    private final GraphService graphService;

    public TreeViewTopComponent() {
        initComponents();
        setName(Bundle.CTL_TreeViewTopComponent());
        setToolTipText(Bundle.HINT_TreeViewTopComponent());
        this.graphService = Lookup.getDefault().lookup(GraphService.class);
        this.explorer = new ExplorerManager();
        this.treeView = new BeanTreeView();
        add(treeView, BorderLayout.CENTER);
    }

    public void updateView() {
        final GraphModel graph = graphService.getModel();
        if (graph == null) {
            final AbstractNode nodeUi = new AbstractNode(Children.LEAF);
            nodeUi.setDisplayName("Missing implementation");
            nodeUi.setName("Root");
            explorer.setRootContext(nodeUi);
        } else {
            final GraphNode root = graph.getRoot();
            if (root == null) {
                final AbstractNode nodeUi = new AbstractNode(Children.LEAF);
                nodeUi.setDisplayName("No graph data");
                nodeUi.setName("Root");
                explorer.setRootContext(nodeUi);
            } else {
                explorer.setRootContext(new GraphNodeUI(root));
            }
        }
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        toolbar = new javax.swing.JToolBar();
        btnRefresh = new javax.swing.JButton();
        btnGraph1 = new javax.swing.JButton();
        filler1 = new javax.swing.Box.Filler(new java.awt.Dimension(5, 0), new java.awt.Dimension(5, 0), new java.awt.Dimension(5, 32767));
        btnGraph2 = new javax.swing.JButton();

        setLayout(new java.awt.BorderLayout());

        toolbar.setFloatable(false);
        toolbar.setRollover(true);

        btnRefresh.setIcon(new javax.swing.ImageIcon(getClass().getResource("/de/btu/swt/graph/ui/Refresh.png"))); // NOI18N
        org.openide.awt.Mnemonics.setLocalizedText(btnRefresh, org.openide.util.NbBundle.getMessage(TreeViewTopComponent.class, "TreeViewTopComponent.btnRefresh.text")); // NOI18N
        btnRefresh.setBorderPainted(false);
        btnRefresh.setFocusable(false);
        btnRefresh.setHorizontalTextPosition(javax.swing.SwingConstants.RIGHT);
        btnRefresh.setVerticalTextPosition(javax.swing.SwingConstants.BOTTOM);
        btnRefresh.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnRefreshActionPerformed(evt);
            }
        });
        toolbar.add(btnRefresh);

        org.openide.awt.Mnemonics.setLocalizedText(btnGraph1, org.openide.util.NbBundle.getMessage(TreeViewTopComponent.class, "TreeViewTopComponent.btnGraph1.text")); // NOI18N
        btnGraph1.setFocusable(false);
        btnGraph1.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        btnGraph1.setVerticalTextPosition(javax.swing.SwingConstants.BOTTOM);
        btnGraph1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnGraph1ActionPerformed(evt);
            }
        });
        toolbar.add(btnGraph1);
        toolbar.add(filler1);

        org.openide.awt.Mnemonics.setLocalizedText(btnGraph2, org.openide.util.NbBundle.getMessage(TreeViewTopComponent.class, "TreeViewTopComponent.btnGraph2.text")); // NOI18N
        btnGraph2.setFocusable(false);
        btnGraph2.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        btnGraph2.setVerticalTextPosition(javax.swing.SwingConstants.BOTTOM);
        btnGraph2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnGraph2ActionPerformed(evt);
            }
        });
        toolbar.add(btnGraph2);

        add(toolbar, java.awt.BorderLayout.PAGE_START);
    }// </editor-fold>//GEN-END:initComponents

    private void btnRefreshActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnRefreshActionPerformed
        updateView();
    }//GEN-LAST:event_btnRefreshActionPerformed

    private void btnGraph1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnGraph1ActionPerformed
        graphService.createDefaultGraph1();
    }//GEN-LAST:event_btnGraph1ActionPerformed

    private void btnGraph2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnGraph2ActionPerformed
        graphService.createDefaultGraph2();
    }//GEN-LAST:event_btnGraph2ActionPerformed

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnGraph1;
    private javax.swing.JButton btnGraph2;
    private javax.swing.JButton btnRefresh;
    private javax.swing.Box.Filler filler1;
    private javax.swing.JToolBar toolbar;
    // End of variables declaration//GEN-END:variables
    @Override
    public void componentOpened() {
        // TODO add custom code on component opening
    }

    @Override
    public void componentClosed() {
        // TODO add custom code on component closing
    }

    void writeProperties(java.util.Properties p) {
        // better to version settings since initial version as advocated at
        // http://wiki.apidesign.org/wiki/PropertyFiles
        p.setProperty("version", "1.0");
        // TODO store your settings
    }

    void readProperties(java.util.Properties p) {
        String version = p.getProperty("version");
        // TODO read your settings according to their version
    }

    @Override
    public ExplorerManager getExplorerManager() {
        return explorer;
    }
}
